### ISSUE TITLE
Not able to remove local storage on close of last window tab  of application

### ISSUE THREAD

**Issue by uyadav0001** [ratnam99/Angular2-JWTSession#1]
Not able to remove local storage on close of last window tab  of application.  So on close of last tab user should be logout automatically. If he forget to logout.

**Comment by ratnam99** [comment]
When you store any data in local storage it remains there unless expired. So, if you want that user data or JWT or any other key is removed when window or tab is closed you need to store it in session storage. 
Here, what you can do is take a variable 'rememberMe' inside local storage and when its value is true (i.e. when user checks the checkbox for keep me signed in), then store the JWT inside local storage, else store the JWT inside session storage.
Thank You. Hope I solved your problem. Please star this repo and let me know about any future problems or bugs anytime. I'll try to solve it asap.
